"""
sse_search.py - Server-side and client-side search operations for the SSE demo.

The *server* executes search() using only the trapdoor token — it never
sees the plaintext keyword.  The *client* uses decrypt_results() to
recover the document content from the returned encrypted identifiers.
"""

from typing import Dict, List

from encryption import decrypt


def search(encrypted_index: Dict[str, List[str]], trapdoor: str) -> List[str]:
    """
    Look up *trapdoor* in the *encrypted_index* and return matching doc IDs.

    This simulates the server-side search: the server compares the trapdoor
    (which is an HMAC token) against the tokens stored in its index.  If
    there is a match it returns the list of encrypted document identifiers.

    The server learns:
      - **Which** documents match (access pattern leakage).
      - **How many** documents match (volume leakage).
      - Whether the **same** trapdoor has been seen before (search pattern leakage).

    Args:
        encrypted_index: token → [encrypted_doc_id, ...] mapping held by the server.
        trapdoor: HMAC token generated by the client for the desired keyword.

    Returns:
        List[str]: Encrypted document ID hex strings for matching documents,
                   or an empty list if no match is found.
    """
    return list(encrypted_index.get(trapdoor, []))


def decrypt_results(
    key: bytes,
    encrypted_doc_ids: List[str],
    document_store: Dict[str, bytes],
) -> List[Dict[str, str]]:
    """
    Decrypt the documents identified by *encrypted_doc_ids*.

    The *client* calls this after receiving the list of encrypted doc IDs
    from the server.  It uses its secret key to decrypt both the document
    identifiers and the document content.

    Args:
        key: 32-byte AES secret key.
        encrypted_doc_ids: List of hex-encoded encrypted doc-ID strings
                           returned by search().
        document_store: Mapping of encrypted_doc_id_hex → encrypted_content
                        (as returned by SearchableIndex.get_document_store()).

    Returns:
        List[dict]: Each dict has ``id`` (str) and ``content`` (str) keys.
    """
    results: List[Dict[str, str]] = []

    for enc_id_hex in encrypted_doc_ids:
        enc_content = document_store.get(enc_id_hex)
        if enc_content is None:
            continue

        # Decrypt the document ID
        doc_id = decrypt(key, bytes.fromhex(enc_id_hex))
        # Decrypt the document content
        doc_content = decrypt(key, enc_content)

        results.append({"id": doc_id, "content": doc_content})

    return results
